# Generated by Django 5.0.2 on 2024-02-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_catalogo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Collezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_collezione', models.CharField(max_length=200)),
                ('img_collezione', models.ImageField(upload_to='')),
                ('nome_catalogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jagobasa.catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prodotto', models.CharField(max_length=100)),
                ('nome_collezione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jagobasa.collezione')),
            ],
        ),
    ]
