# Generated by Django 5.0.2 on 2024-02-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogo',
            old_name='nome_catalogo',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='collezione',
            old_name='nome_catalogo',
            new_name='catalogo',
        ),
        migrations.RenameField(
            model_name='collezione',
            old_name='img_collezione',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='collezione',
            old_name='nome_collezione',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='prodotto',
            old_name='nome_collezione',
            new_name='collezione',
        ),
        migrations.RenameField(
            model_name='prodotto',
            old_name='nome_prodotto',
            new_name='nome',
        ),
        migrations.CreateModel(
            name='Prodottoimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('prodotto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jagobasa.prodotto')),
            ],
        ),
    ]
