# Generated by Django 5.0.2 on 2024-02-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0002_rename_nome_catalogo_catalogo_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottoimg',
            name='prodotto_nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
