# Generated by Django 5.0.2 on 2024-02-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0003_prodottoimg_prodotto_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodottoimg',
            old_name='prodotto_nome',
            new_name='img_nome',
        ),
    ]
