# Generated by Django 5.0.2 on 2024-02-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0004_rename_prodotto_nome_prodottoimg_img_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='collezione',
            name='nome_img',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collezione',
            name='image',
            field=models.ImageField(upload_to='jagobasa/static/img_collezione'),
        ),
        migrations.AlterField(
            model_name='collezione',
            name='nome',
            field=models.CharField(max_length=500),
        ),
    ]
