# Generated by Django 5.0.2 on 2024-02-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0005_collezione_nome_img_alter_collezione_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collezione',
            old_name='nome_img',
            new_name='nomeimg',
        ),
    ]
