# Generated by Django 5.0.2 on 2024-03-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0006_rename_nome_img_collezione_nomeimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collezione',
            name='nomeimg',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='order',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
