# Generated by Django 5.0.2 on 2024-03-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0007_remove_collezione_nomeimg_catalogo_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('ita', models.CharField(max_length=100, null=True)),
                ('eng', models.CharField(max_length=100, null=True)),
                ('rus', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='catalogo',
            name='order',
        ),
        migrations.AlterField(
            model_name='prodottoimg',
            name='image',
            field=models.ImageField(upload_to='jagobasa/static/img_prodotti'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jagobasa.tipo'),
        ),
    ]
