# Generated by Django 5.0.2 on 2024-03-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0008_tipo_remove_catalogo_order_alter_prodottoimg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='image',
            field=models.ImageField(default='', upload_to='jagobasa/static/img_tipi'),
        ),
    ]
