# Generated by Django 5.0.2 on 2024-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0010_remove_prodotto_tipo_prodotto_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='collezione',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['tipo']},
        ),
        migrations.AddField(
            model_name='catalogo',
            name='image',
            field=models.ImageField(default='', upload_to='jagobasa/static/img_catalogo'),
        ),
    ]
