# Generated by Django 5.0.2 on 2024-03-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0011_alter_catalogo_options_alter_collezione_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='collezione',
            name='catalogo',
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='tipo',
            field=models.ManyToManyField(help_text='Select a tipo for this prodotto', to='jagobasa.tipo'),
        ),
        migrations.AddField(
            model_name='collezione',
            name='catalogo',
            field=models.ManyToManyField(help_text='Select a catalogo for this collection', to='jagobasa.catalogo'),
        ),
    ]
