# Generated by Django 5.0.2 on 2024-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0012_alter_catalogo_options_remove_collezione_catalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collezione',
            name='image_back',
            field=models.ImageField(default='', upload_to='jagobasa/static/img_col_back'),
        ),
    ]
