# Generated by Django 5.0.2 on 2024-03-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0014_alter_prodottoimg_options_prodottodet_prodottoluc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodottodet',
            name='catena',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prodottodet',
            name='materiale',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prodottodet',
            name='variante',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
