# Generated by Django 5.0.2 on 2024-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0015_alter_prodottodet_catena_alter_prodottodet_materiale_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodottodet',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='prodottodet',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prodottoluc',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prodottodet',
            name='catena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prodottodet',
            name='forma',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='prodottodet',
            name='materiale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prodottodet',
            name='variante',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
