# Generated by Django 5.0.2 on 2024-03-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0016_alter_prodottodet_options_prodottodet_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodottoluc',
            options={'ordering': ['nome']},
        ),
    ]
