# Generated by Django 5.0.3 on 2024-03-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0017_alter_prodottoluc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='jagobasa/static/img_catalogo'),
        ),
    ]
