# Generated by Django 5.0.3 on 2024-03-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0018_alter_catalogo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdottoSchede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheda_nome', models.CharField(max_length=100, null=True)),
                ('scheda', models.ImageField(upload_to='jagobasa/static/img_schede')),
                ('scheda_blanc', models.ImageField(upload_to='jagobasa/static/img_schede_blanche')),
                ('prodotto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jagobasa.prodotto')),
            ],
            options={
                'ordering': ['scheda_nome'],
            },
        ),
    ]
