# Generated by Django 5.0.3 on 2024-03-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0019_prodottoschede'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoStanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanza', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='', upload_to='jagobasa/static/img_stanze')),
                ('ita', models.CharField(max_length=100, null=True)),
                ('eng', models.CharField(max_length=100, null=True)),
                ('rus', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['stanza'],
            },
        ),
        migrations.AlterField(
            model_name='prodottoschede',
            name='scheda_blanc',
            field=models.ImageField(default='', null=True, upload_to='jagobasa/static/img_schede_blanche'),
        ),
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='jagobasa/static/img_progetti')),
                ('testo', models.TextField(blank=True, max_length=1000, null=True)),
                ('stanza', models.CharField(max_length=100, null=True)),
                ('prodotto', models.ManyToManyField(help_text='Scegli i progetti per questo prodotto', to='jagobasa.prodotto')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
