# Generated by Django 5.0.3 on 2024-03-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0021_tipo_ukr_tipostanza_ukr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progetto',
            name='stanza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jagobasa.tipostanza'),
        ),
    ]
