# Generated by Django 5.0.3 on 2024-03-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0022_alter_progetto_stanza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodottoschede',
            old_name='scheda',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='prodottoschede',
            old_name='scheda_blanc',
            new_name='image_blanc',
        ),
    ]
