# Generated by Django 5.0.3 on 2024-03-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0023_rename_scheda_prodottoschede_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipostanza',
            options={'ordering': ['nome']},
        ),
        migrations.RenameField(
            model_name='tipostanza',
            old_name='stanza',
            new_name='nome',
        ),
    ]
