# Generated by Django 5.0.3 on 2024-03-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0024_alter_tipostanza_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodotto',
            options={'ordering': ['novita', 'nome']},
        ),
        migrations.AddField(
            model_name='prodotto',
            name='novita',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
