# Generated by Django 5.0.3 on 2024-03-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0025_alter_prodotto_options_prodotto_novita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodotto',
            options={'ordering': ['-novita', 'nome']},
        ),
    ]
