# Generated by Django 5.0.3 on 2024-03-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0026_alter_prodotto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['-status', 'id']},
        ),
        migrations.AlterModelOptions(
            name='collezione',
            options={'ordering': ['-status', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'ordering': ['-status', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='progetto',
            options={'ordering': ['-status', 'nome']},
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='novita',
        ),
        migrations.AddField(
            model_name='catalogo',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='collezione',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='progetto',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
