# Generated by Django 5.0.3 on 2024-03-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0027_alter_catalogo_options_alter_collezione_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collezione',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='eng',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='ita',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='rus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='ukr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
