# Generated by Django 5.0.3 on 2024-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0030_alter_prodotto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['status', 'id']},
        ),
        migrations.AddField(
            model_name='prodotto',
            name='preise',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
