# Generated by Django 5.0.3 on 2024-05-30 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0031_alter_catalogo_options_prodotto_preise'),
    ]

    operations = [

        migrations.AddField(
            model_name='prodottoimg',
            name='image_ico',
            field=models.ImageField(default='', upload_to='jagobasa/static/img_prod_ico'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='prodottodet',
            name='forma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prodottoimg',
            name='image',
            field=models.ImageField(default='', upload_to='jagobasa/static/img_prodotti'),
        ),
        migrations.CreateModel(
            name='CatalogoBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('pagina', models.CharField(max_length=20, null=True)),
                ('image_pag', models.ImageField(default='', null=True, upload_to='jagobasa/static/img_cat_pag')),
                ('catalogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jagobasa.catalogo')),
            ],
            options={
                'ordering': ['nome', 'pagina'],
            },
        ),
    ]
