# Generated by Django 5.0.3 on 2024-05-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0031_alter_catalogo_options_prodotto_preise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
