# Generated by Django 5.0.3 on 2024-05-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0031_alter_catalogo_options_prodotto_preise'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottodet',
            name='altezza',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='prodottodet',
            name='messura',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='prodottoimg',
            name='image_ico',
            field=models.ImageField(default='', upload_to='jagobasa/static/img_prod_ico'),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='prodottodet',
            name='forma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prodottoimg',
            name='image',
            field=models.ImageField(default='', upload_to='jagobasa/static/img_prodotti'),
        ),
    ]
