# Generated by Django 4.2.13 on 2024-06-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0032_prodottodet_altezza_prodottodet_messura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('pagina', models.CharField(max_length=20, null=True)),
                ('titolo', models.CharField(max_length=20, null=True)),
                ('image_pag', models.ImageField(default='', null=True, upload_to='jagobasa/static/img_cat_pag')),
                ('catalogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jagobasa.catalogo')),
            ],
            options={
                'ordering': ['nome', 'pagina'],
            },
        ),
    ]
