# Generated by Django 5.0.3 on 2024-05-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0032_prodottodet_altezza_prodottodet_messura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottodet',
            name='altezza',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='prodottodet',
            name='messura',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
