# Generated by Django 5.0.3 on 2024-05-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0032_alter_prodotto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottoimg',
            name='image_ico',
            field=models.ImageField(default='', upload_to='jagobasa/static/img_prod_ico'),
        ),
        migrations.AlterField(
            model_name='prodottoimg',
            name='image',
            field=models.ImageField(default='', upload_to='jagobasa/static/img_prodotti'),
        ),
    ]
