# Generated by Django 5.0.3 on 2024-05-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0033_prodottodet_altezza_prodottodet_messura'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogobook',
            name='titolo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
