# Generated by Django 5.0.3 on 2024-05-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0033_prodottoimg_image_ico_alter_prodottoimg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottodet',
            name='altezza',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='prodottodet',
            name='messura',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
