# Generated by Django 5.0.3 on 2024-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0034_prodottodet_altezza_prodottodet_messura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodottodet',
            options={'ordering': ['nome', 'forma']},
        ),
        migrations.AlterField(
            model_name='prodottodet',
            name='forma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
