# Generated by Django 5.0.3 on 2024-05-17 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0034_prodottodet_altezza_prodottodet_messura'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottodet',
            name='collezione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jagobasa.collezione'),
        ),
        migrations.AddField(
            model_name='prodottoluc',
            name='collezione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jagobasa.collezione'),
        ),
    ]
