# Generated by Django 5.0.3 on 2024-05-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0036_remove_prodottodet_collezione_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodottodet',
            options={'ordering': ['nome', 'forma']},
        ),
    ]
