# Generated by Django 5.0.3 on 2024-05-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jagobasa', '0037_alter_prodottodet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodottodet',
            name='forma',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
